import express from "express";
import { addBuyAnimal, getBuyAnimal, deleteBuyAnimal, increaseBuyAnimalQty, decreaseBuyAnimalQty, getAllBuyAnimal, getBuyAnimalById } from "../controller/BuyAnimalController.js";
import {authenticateToken} from "../middlware/VerifyToken.js";
const BuyAnimalRoute = express.Router();
BuyAnimalRoute.post("/buyanimal/:animalId",authenticateToken,addBuyAnimal);
BuyAnimalRoute.get("/getbuyanimal", authenticateToken, getBuyAnimal);
BuyAnimalRoute.get("/getbuyanimalbyid/:id", authenticateToken, getBuyAnimalById);
BuyAnimalRoute.delete("/deletebuyanimal/:id", authenticateToken, deleteBuyAnimal);
BuyAnimalRoute.get("/getallbuyanimal", authenticateToken, getAllBuyAnimal);
BuyAnimalRoute.put("/increasebuyanimalqty/:id", authenticateToken, increaseBuyAnimalQty);
BuyAnimalRoute.put("/decreasebuyanimalqty/:id", authenticateToken, decreaseBuyAnimalQty);
export default BuyAnimalRoute;