import express from "express";
import { loginUser, logoutUser, registerUser, deleteUser, verifyOtp, getAllUsers, verifyUser, getProfile, updateProfile, deleteProfile } from "../controller/UserController.js";
import { authenticateToken } from "../middlware/VerifyToken.js";
const userRouter = express.Router();
userRouter.post("/register", registerUser);
userRouter.post("/login", loginUser);
userRouter.post("/logout", logoutUser);
userRouter.delete("/delete/:id", deleteUser);
userRouter.get("/all-users", getAllUsers);
userRouter.post("/verify-otp", verifyOtp);
userRouter.get("/verify-user", authenticateToken, verifyUser);
userRouter.get("/get-profile", getProfile);
userRouter.put("/update-profile", updateProfile);
userRouter.delete("/delete-profile", deleteProfile);
export default userRouter;